authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path(
        'dashboard/recipe/new/', 
        views.DashBoardRecipe.as_view(), 
        name='dashboard_recipe_new'),
    path(
        'dashboard/recipe/delete/', 
        views.DashBoardRecipeDelete.as_view(), 
        name='dashboard_recipe_delete'
    ),
    path(
        'dashboard/recipe/<int:id>/edit/', 
        views.DashBoardRecipe.as_view(), 
        name='dashboard_recipe_edit'
    ), 
    path(
        'profile/<int:id>/', 
        views.ProfileView.as_view(), 
        name='profile'
    ), 
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'


urlpatterns = [
    path('', views.RecipeListViewHome.as_view(), name="home"),
    path('recipes/search/', views.RecipeListViewSearch.as_view(), name='search'),
    path('recipes/tag/<slug:slug>', views.RecipeListViewTag.as_view(), name='tag'),
    path('recipes/category/<int:category_id>/', views.RecipeListViewCategory.as_view(), name="category"),
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name="recipe"),
    path('recipes/api/v1/', views.RecipeListViewHomeApi.as_view(), name="api_v1"),
    path('recipes/api/v1/<int:pk>/', views.RecipeDetailApi.as_view(), name="api_v1_detail"),
    path('recipes/theory/', views.theory, name="theory"),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from tag.models import Tag
from django.utils.translation import gettext_lazy as _
import os
from django.conf import settings
from PIL import Image
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=70)
    
    def __str__(self) -> str:
        return self.name

    

class Recipe(models.Model):
    title = models.CharField(max_length=70, verbose_name=_('Title'))
    description = models.CharField(max_length=170)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=70)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=70)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True,
                                blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True, default='')
    
    def __str__(self) -> str:
        return self.title
    
    
    @staticmethod
    def resize_image(image, new_width=800):
        image_full_path = os.path.join(settings.MEDIA_ROOT, image.name)
        image_pillow = Image.open(image_full_path)
        original_width, original_height = image_pillow.size
        
        if original_width < new_width:
            image_pillow.close()
            return
        
        new_height = round((new_width * original_height) / original_width)
        new_image = image_pillow.resize((new_width, new_height), Image.LANCZOS)
        new_image.save(
            image_full_path,
            optimize=True,
            quality=50,
        )
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = f'{slugify(self.title)}'
            
        saved = super().save(*args, **kwargs)
        
        if self.cover:
            try:
                self.resize_image(self.cover, 840)
            except FileNotFoundError:
                ...
                
        return saved
     
        
    def get_absolute_url(self):
        return reverse('recipes:recipe', args=(self.id,))
    
    
    class Meta:
        verbose_name = _('Recipe')
        verbose_name_plural = _('Recipes')
    
        
    

authors/forms/recipe_form.py
from django import forms
from recipes.models import Recipe
from utils.recipes.django_forms import add_attr
from utils.recipes.vstrings import is_positive_number
from collections import defaultdict
from django.core.exceptions import ValidationError

class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self._merrors = defaultdict(list)
        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')
        
        
        
    class Meta:
        model = Recipe
        fields = (
            'title', 'description', 'preparation_time',
            'preparation_time_unit', 'servings', 'servings_unit',
            'preparation_steps', 'cover',
        )
        
        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoas', 'Pessoas'),
                )
            ),
            
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                )
            )
        }
        
        
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        
        cd = self.cleaned_data
        title = cd.get('title')
        description = cd.get('description')
        
        if title is None or len(title) < 5:
            self._merrors['title'].append('Title must have at least 5 characters.')
        
        if title == description:
            self._merrors['title'].append('Title can not be equal to description.')
            self._merrors['description'].append('Description can not be equal to title.')
            
            
            
        if self._merrors:
            raise ValidationError(self._merrors)
        
            
        return super_clean
    
    def clean_preparation_time(self):
        preparation_time = self.cleaned_data.get('preparation_time')
        
        if not is_positive_number(preparation_time):
            self._merrors['preparation_time'].append('Must be a positive number.')
            
        return preparation_time
            
            

recipes/views.py
from typing import Any, Dict
from django import http
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Recipe
from django.db.models import Q
from utils.recipes.pagination import make_pagination
import os
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.shortcuts import render
from tag.models import Tag
from django.utils import translation
from django.utils.translation import gettext as _
# Create your views here.


PER_PAGE = int(os.environ.get('PER_PAGE', 5))

def theory(request, *args, **kwargs):
        recipes = Recipe.objects.all() 
        
        context = {'recipes': recipes}
        return render(
                request, 
                'recipes/pages/theory.html',
                context=context,
        )

class RecipeListViewBase(ListView):
        model = Recipe
        context_object_name = 'recipes'
        ordering = ['-id']
        template_name = 'recipes/pages/home.html'
        
        def get_queryset(self, *args, **kwargs):
            qs = super().get_queryset(*args, **kwargs)
            qs = qs.filter(
                    is_published=True,
            )
            
            qs = qs.select_related('author', 'category')
            qs = qs.prefetch_related('tags', 'author__profile')
            return qs
    
        def get_context_data(self, *args, **kwargs):
             ctx = super().get_context_data(*args, **kwargs)
             page_obj, pagination_range = make_pagination(
                     self.request, 
                     ctx.get('recipes'), 
                     PER_PAGE
                )
             
             html_language = translation.get_language()
             
             ctx.update({
                     'recipes': page_obj,
                     'pagination_range':  pagination_range,
                     'html_language': html_language,
                     })

             return ctx
                
                
class RecipeListViewHome(RecipeListViewBase):
        template_name = 'recipes/pages/home.html'
        
class RecipeListViewHomeApi(RecipeListViewBase):
        template_name = 'recipes/pages/home.html'
        
        def render_to_response(self, context, **response_kwargs):
                recipes = self.get_context_data()['recipes']
                recipes_list = recipes.object_list.values()
                
                return JsonResponse(
                list(recipes_list),
                safe=False,
        )
        

class RecipeListViewCategory(RecipeListViewBase):
        template_name = 'recipes/pages/category.html'
        
        def get_context_data(self, *args, **kwargs):
             ctx = super().get_context_data(*args, **kwargs)
             category_translation = _('Category')
             ctx.update({
                'title': f'{ctx.get("recipes")[0].category.name} - {category_translation} |'
        })

             return ctx 
        
        def get_queryset(self, *args, **kwargs):
            qs = super().get_queryset(*args, **kwargs)
            
            qs = qs.filter(
                    category__id=self.kwargs.get('category_id'),
                    is_published=True,
            )
            
            if not qs:
                raise Http404()
            
            return qs
    
       
class RecipeListViewSearch(RecipeListViewBase):
        template_name = 'recipes/pages/search.html'      
        
        def get_queryset(self, *args, **kwargs):
            search_term = self.request.GET.get('q', '')
            
            if not search_term:
                raise Http404()
            
            qs = super().get_queryset(*args, **kwargs)
            qs = qs.filter(
                Q(  
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term), 
              )
            )
            
            return qs  
    
    
        def get_context_data(self, *args, **kwargs):
             ctx = super().get_context_data(*args, **kwargs)
             
             search_term = self.request.GET.get('q', '')
             
             ctx.update({
                'page_title': f'Search for "{search_term}"',
                'search_term': search_term,
                'additional_url_query': f'&q={search_term}'
                })

             return ctx
     
    
    
class RecipeDetail(DetailView):
        model = Recipe
        context_object_name = 'recipe'
        template_name = 'recipes/pages/recipe-view.html'
        
        
        def get_queryset(self, *args, **kwargs):
                qs = super().get_queryset(*args, **kwargs)
                qs = qs.filter(is_published=True)
                
                return qs
                
                
        def get_context_data(self, *args, **kwargs):
                ctx = super().get_context_data(*args, **kwargs)
                
                ctx.update({
                        'is_detail_page': True,  
                })
                
                return ctx
        
    
class RecipeDetailApi(RecipeDetail):
        def render_to_response(self, context, **response_kwargs):
                recipe = self.get_context_data()['recipe']
                recipe_dict = model_to_dict(recipe) 
                recipe_dict['created_at'] = str(recipe.created_at)
                recipe_dict['updated_at'] = str(recipe.updated_at)
                
                if recipe_dict.get('cover'):
                        recipe_dict['cover'] = self.request.build_absolute_uri() + recipe_dict['cover'].url[1:]
                else:
                       recipe_dict['cover'] = '' 
                       
                del recipe_dict['is_published']
                del recipe_dict["preparation_steps_is_html"]
                
                return JsonResponse(recipe_dict, 
                                    safe=False
                        )


class RecipeListViewTag(RecipeListViewBase):
        template_name = 'recipes/pages/tag.html'      
        
        def get_queryset(self, *args, **kwargs):


            qs = super().get_queryset(*args, **kwargs)
            qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
            
            return qs  
    
    
        def get_context_data(self, *args, **kwargs):
             ctx = super().get_context_data(*args, **kwargs)
             
             page_title = Tag.objects.filter(slug=self.kwargs.get('slug', '')).first()
             
             if not page_title:
                     page_title = 'No recipes found'
                     
             page_title = f'{page_title} - Tag |'
             
             ctx.update({
                'page_title': {page_title},
                })

             return ctx
     

recipes/templates/recipes/partials/_head.html
{% load static %}


<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css" integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/brands.min.css" integrity="sha512-+oRH6u1nDGSm3hH8poU85YFIVTdSnS2f+texdPGrURaJh8hzmhMiZrQth6l56P4ZQmxeZzd2DqVEMqQoJ8J89A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css" integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/_recipe.html
{% load i18n %}


<div class="recipe recipe-list-item">
    {% if recipe.cover %}

        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Placeholder">
            </a>
        </div>

    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}"> 
                {{ recipe.title }} 
            </a>
        </h2>
    </div>

    <div class="recipe-author">

        {% if recipe.author %}
            <span class="recipe-author-item">
                {% if recipe.author.profile %}
                
                    <a href="{% url 'authors:profile' recipe.author.profile.id %}">

                {% endif %}

                <i class="fas fa-user"></i>

                {% if recipe.author.first_name %}

                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}

                {% else %}

                    {{ recipe.author.username }}

                {% endif %}

                {% if recipe.author.profile %}
                    </a>
                {% endif %}

            </span>
        {% endif %}
        
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>

        {% if recipe.category.id is not None %}

            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>

        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fas fa-stopwatch"></i>
                {% translate 'Preparation' %}
            </h3>
            <div class="recipe-meta-text">{{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}</div>
        </div>
        

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-pizza-slice"></i>
                {% translate 'Servings' %}
            </h3>
            <div class="recipe-meta-text">{{ recipe.servings }} {{ recipe.servings_unit }}</div>
        </div>

        

    </div>

    {% if not is_detail_page %}

        <footer class="recipe-footer">
            <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                <i class="fas fa-eye"></i>
                <span>{% translate 'read more' %}...</span>
            </a>
        </footer>

    {% endif %}

    {% if is_detail_page %}
        <div class="preparation-steps">

        {% if recipe.preparation_steps_is_html %}

            {{ recipe.preparation_steps }}
           
        {% else %}
           
            {{ recipe.preparation_steps|linebreaksbr }}

        {% endif %}
        
        {% if recipe.tags.all %}
        <p>Tags:
            {% for tag in recipe.tags.all %}
                <a href="{% url 'recipe:tag' tag.slug %}">
                    {{ tag.name }}
                </a>,
            {% endfor %}
        </p>

        {% endif %}
        </div>

    {% endif %}

</div>